INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('teach for america', 'education', 10000, 122016, 040217);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('girls can code', 'tech-ed', 2500, 032115, 022717);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('lupus foundation', 'health', 7500, 062115, 122717);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('leadership 2.0', 'personal development', 8300, 122115, 012717);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('peace corps', 'humanity', 12500, 052115, 112717);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('runners', 'fitness', 500, 122114, 072717);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('www', 'tech-ed', 5500, 092116, 022717);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('save the children', 'humanity', 10500, 042115, 092717);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('girls can code', 'tech-ed', 2500, 032115, 022717);
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ('girls can code', 'tech-ed', 2500, 032115, 022717);

INSERT INTO users (name, age) VALUES ('Rebecca', 24);
INSERT INTO users (name, age) VALUES ('Paige', 35);
INSERT INTO users (name, age) VALUES ('Robert', 46);
INSERT INTO users (name, age) VALUES ('Matthew', 28);
INSERT INTO users (name, age) VALUES ('Greg', 39);
INSERT INTO users (name, age) VALUES ('David', 19);
INSERT INTO users (name, age) VALUES ('Samantha', 32);
INSERT INTO users (name, age) VALUES ('Daniel', 30);
INSERT INTO users (name, age) VALUES ('Aubrey', 23);
INSERT INTO users (name, age) VALUES ('James', 35);
INSERT INTO users (name, age) VALUES ('John', 33);
INSERT INTO users (name, age) VALUES ('Natasha', 28);
INSERT INTO users (name, age) VALUES ('Patricia', 59);
INSERT INTO users (name, age) VALUES ('Charles', 44);
INSERT INTO users (name, age) VALUES ('Grace', 29);
INSERT INTO users (name, age) VALUES ('Alice', 24);
INSERT INTO users (name, age) VALUES ('Peter', 65);
INSERT INTO users (name, age) VALUES ('Pam', 37);
INSERT INTO users (name, age) VALUES ('Kristen', 32);
INSERT INTO users (name, age) VALUES ('Jeremy', 31);


INSERT INTO pledges (amount, user_id, project_id) VALUES ( 35, 1, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1500, 1, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (300, 12, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (900, 20, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 16, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (750, 7, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 17, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 1, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 13, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (45, 15, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (55, 10, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (60, 19, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 19, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 18, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 4, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 12, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 15, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (600, 20, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (800, 17, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1500, 2, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (200, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (75, 4, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (5, 16, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (1200, 7, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (250, 9, 2);
